services:
  pc_noetic_container:
    image: pc_noetic_image
    container_name: pc_noetic_container
    network_mode: host
    environment:
      - ROS_IPV6=on # Opcional
      - ROS_MASTER_URI=http://192.168.0.61:11311 # Usando la IP del robot (RECOMENDADO)
      - ROS_HOSTNAME=pc_node # Nombre descriptivo para el nodo en el PC (RECOMENDADO)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
    