name: rubot-noetic
services:
  rubot_ros_noetic_service:
    image: rubot_ros_noetic_image  # No explicit "latest" tag
    privileged: true
    network_mode: host
    container_name: rubot_ros_noetic_container
    environment:
      - ROS_IPV6=on
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ./rubot_bringup.sh:/root/rubot_bringup.sh:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
    entrypoint: /ros_entrypoint.sh
    command: ["/root/rubot_bringup.sh"]
    restart: always  # Automatically restart on error or system boot
